Pandas module like CSV Parser: KSingleVectorComponent Class Reference
KSingleVectorComponent Class Reference
#include <KDataFrame.h>
Public Member Functions
KSingleVectorComponent ()=default
デフォルトコンストラクタ
~KSingleVectorComponent ()=default
デストラクタ
KSingleVectorComponent (std::initializer_list< std::string > list)
引数付きコンストラクタ
KSingleVectorComponent (const KSingleVectorComponent &obj)=default
コピーコンストラクタ
template<typename T >
void push_back (const T &val)
値の追加.
void push_back (const char *val)
void push_back (const std::string &val)
template<typename T >
void append (const T &val)
値の追加
void append (const char *val)
void append (const std::string &val)
void Scan ()
template<typename T >
std::vector< T > AsType ()
値のキャスト
KSingleVectorComponent & operator= (const KSingleVectorComponent &Obj)=default
= 演算子のオーバーロード
Detailed Description
Definition at line 522 of file KDataFrame.h.
Constructor & Destructor Documentation
KSingleVectorComponent() [1/3]
KSingleVectorComponent::KSingleVectorComponent () default
デフォルトコンストラクタ
~KSingleVectorComponent()
KSingleVectorComponent::~KSingleVectorComponent () default
デストラクタ
KSingleVectorComponent() [2/3]
KSingleVectorComponent::KSingleVectorComponent (std::initializer_list< std::string > list) inline
引数付きコンストラクタ
Definition at line 533 of file KDataFrame.h.
KSingleVectorComponent() [3/3]
KSingleVectorComponent::KSingleVectorComponent (const KSingleVectorComponent & obj) default
コピーコンストラクタ
Member Function Documentation
append() [1/3]
void KSingleVectorComponent::append (const char * val) inline
Definition at line 543 of file KDataFrame.h.
append() [2/3]
void KSingleVectorComponent::append (const std::string & val) inline
Definition at line 544 of file KDataFrame.h.
append() [3/3]
template<typename T > void KSingleVectorComponent::append (const T & val) inline
値の追加
push_back関数と同じ.
Definition at line 575 of file KDataFrame.h.
References push_back().
AsType()
template<typename T > std::vector< T > KSingleVectorComponent::AsType ()
値のキャスト
Definition at line 581 of file KDataFrame.h.
References KStringFmt::StringTo().
operator=()
KSingleVectorComponent & KSingleVectorComponent::operator= (const KSingleVectorComponent & Obj) default
= 演算子のオーバーロード
push_back() [1/3]
void KSingleVectorComponent::push_back (const char * val) inline
Definition at line 540 of file KDataFrame.h.
push_back() [2/3]
void KSingleVectorComponent::push_back (const std::string & val) inline
Definition at line 541 of file KDataFrame.h.
push_back() [3/3]
template<typename T > void KSingleVectorComponent::push_back (const T & val) inline
値の追加.
Definition at line 566 of file KDataFrame.h.
Referenced by append().
Scan()
void KSingleVectorComponent::Scan ()
Definition at line 556 of file KDataFrame.h.
The documentation for this class was generated from the following file:
header/KDataFrame.h