Pandas module like CSV Parser: KIndexArray Class Reference
KIndexArray Class Reference
配列の添字を記録する
#include <KDataFrame.h>
Public Member Functions
KIndexArray ()=default
デフォルトコンストラクタ
KIndexArray (const std::vector< int > index)
引数付きコンストラクタ
~KIndexArray ()=default
デストラクタ
KIndexArray (const KIndexArray &obj)=default
コピーコンストラクタ
size_t Size () const
bool Empty () const
void Scan ()
void push_back (int val)
void Set (std::size_t i, int val)
int Get (std::size_t i) const
KIndexArray & operator= (const KIndexArray &obj)=default
int & operator[] (std::size_t i)
const int & operator[] (std::size_t i) const
Detailed Description
配列の添字を記録する
Definition at line 140 of file KDataFrame.h.
Constructor & Destructor Documentation
KIndexArray() [1/3]
KIndexArray::KIndexArray () default
デフォルトコンストラクタ
KIndexArray() [2/3]
KIndexArray::KIndexArray (const std::vector< int > index) inline
引数付きコンストラクタ
Definition at line 148 of file KDataFrame.h.
~KIndexArray()
KIndexArray::~KIndexArray () default
デストラクタ
KIndexArray() [3/3]
KIndexArray::KIndexArray (const KIndexArray & obj) default
コピーコンストラクタ
Member Function Documentation
Empty()
bool KIndexArray::Empty () const inline
Definition at line 155 of file KDataFrame.h.
Get()
int KIndexArray::Get (std::size_t i) const inline
Definition at line 169 of file KDataFrame.h.
operator=()
KIndexArray & KIndexArray::operator= (const KIndexArray & obj) default
operator[]() [1/2]
int & KIndexArray::operator[] (std::size_t i) inline
Definition at line 172 of file KDataFrame.h.
operator[]() [2/2]
const int & KIndexArray::operator[] (std::size_t i) const inline
Definition at line 173 of file KDataFrame.h.
push_back()
void KIndexArray::push_back (int val) inline
Definition at line 167 of file KDataFrame.h.
Referenced by KSingleVector< T >::operator!=(), KSingleVector< T >::operator<(), KSingleVector< T >::operator==(), and KSingleVector< T >::operator>().
Scan()
void KIndexArray::Scan () inline
Definition at line 156 of file KDataFrame.h.
Set()
void KIndexArray::Set (std::size_t i, int val) inline
Definition at line 168 of file KDataFrame.h.
Size()
size_t KIndexArray::Size () const inline
Definition at line 154 of file KDataFrame.h.
Referenced by KSingleVector< T >::operator[]().
The documentation for this class was generated from the following file:
header/KDataFrame.h