Pandas module like CSV Parser: KSingleVector< T > Class Template Reference
KSingleVector< T > Class Template Reference
四則演算用クラス
#include <KDataFrame.h>
Public Member Functions
KSingleVector ()=default
デフォルトコンストラクタ
~KSingleVector ()=default
デストラクタ
KSingleVector (std::initializer_list< T > list)
引数付きコンストラクタ
KSingleVector (const std::vector< T > list)
引数付きコンストラクタ
KSingleVector (const KSingleVector &obj)=default
引数付きコンストラクタ
size_t Size ()
bool Empty ()
void Scan ()
std::vector< T > ToVector ()
std::vector<T>で取得
T & GetValue (std::size_t i)
const T & GetValue (std::size_t i) const
void push_back (const T &val)
値の追加.
void append (const T &val)
値の追加
template<typename To >
KSingleVector< To > AsType ()
キャストします.
KSingleVector & operator= (const KSingleVector &obj)=default
= 演算子のオーバーロード
KSingleVector & operator= (const std::vector< T > &obj)
T & operator[] (std::size_t i)
const T & operator[] (std::size_t i) const
KSingleVector< T > operator+ (const KSingleVector< T > &obj) const
KSingleVector< T > operator- (const KSingleVector< T > &obj) const
KSingleVector< T > operator* (const KSingleVector< T > &obj) const
KSingleVector< T > operator/ (const KSingleVector< T > &obj) const
KSingleVector< T > operator+ (const T val) const
KSingleVector< T > operator- (const T val) const
KSingleVector< T > operator* (const T val) const
KSingleVector< T > operator/ (const T val) const
KSingleVector< T > operator== (const T val) const
KSingleVector< T > operator!= (const T val) const
KSingleVector< T > operator> (const T val) const
KSingleVector< T > operator< (const T val) const
KSingleVector< T > operator>= (const T val) const
KSingleVector< T > operator<= (const T val) const
Detailed Description
template<typename T = std::string>
class KSingleVector< T >
四則演算用クラス
Definition at line 132 of file KDataFrame.h.
Constructor & Destructor Documentation
KSingleVector() [1/4]
template<typename T = std::string> KSingleVector< T >::KSingleVector () default
デフォルトコンストラクタ
~KSingleVector()
template<typename T = std::string> KSingleVector< T >::~KSingleVector () default
デストラクタ
KSingleVector() [2/4]
template<typename T = std::string> KSingleVector< T >::KSingleVector (std::initializer_list< T > list) inline
引数付きコンストラクタ
Definition at line 142 of file KDataFrame.h.
KSingleVector() [3/4]
template<typename T = std::string> KSingleVector< T >::KSingleVector (const std::vector< T > list) inline
引数付きコンストラクタ
Definition at line 147 of file KDataFrame.h.
KSingleVector() [4/4]
template<typename T = std::string> KSingleVector< T >::KSingleVector (const KSingleVector< T > & obj) default
引数付きコンストラクタ
コピーコンストラクタ
Member Function Documentation
append()
template<typename T > void KSingleVector< T >::append (const T & val) inline
値の追加
push_back関数と同じ.
Definition at line 244 of file KDataFrame.h.
References KSingleVector< T >::push_back(), and StringTo().
AsType()
template<typename T > template<typename To > KSingleVector< To > KSingleVector< T >::AsType ()
キャストします.
Definition at line 213 of file KDataFrame.h.
References KSingleVector< T >::push_back(), and StringTo().
Empty()
template<typename T = std::string> bool KSingleVector< T >::Empty () inline
Definition at line 154 of file KDataFrame.h.
GetValue() [1/2]
template<typename T = std::string> T & KSingleVector< T >::GetValue (std::size_t i) inline
Definition at line 160 of file KDataFrame.h.
References StringTo().
GetValue() [2/2]
template<typename T = std::string> const T & KSingleVector< T >::GetValue (std::size_t i) const inline
Definition at line 161 of file KDataFrame.h.
References StringTo().
operator!=()
template<typename T > KSingleVector< T > KSingleVector< T >::operator!= (const T val) const inline
Definition at line 339 of file KDataFrame.h.
References KSingleVector< T >::push_back(), and StringTo().
operator*() [1/2]
template<typename T > KSingleVector< T > KSingleVector< T >::operator* (const KSingleVector< T > & obj) const inline
Definition at line 280 of file KDataFrame.h.
References StringTo().
operator*() [2/2]
template<typename T > KSingleVector< T > KSingleVector< T >::operator* (const T val) const inline
Definition at line 316 of file KDataFrame.h.
References StringTo().
operator+() [1/2]
template<typename T > KSingleVector< T > KSingleVector< T >::operator+ (const KSingleVector< T > & obj) const inline
Definition at line 260 of file KDataFrame.h.
References StringTo().
operator+() [2/2]
template<typename T > KSingleVector< T > KSingleVector< T >::operator+ (const T val) const inline
Definition at line 300 of file KDataFrame.h.
References StringTo().
operator-() [1/2]
template<typename T > KSingleVector< T > KSingleVector< T >::operator- (const KSingleVector< T > & obj) const inline
Definition at line 270 of file KDataFrame.h.
References StringTo().
operator-() [2/2]
template<typename T > KSingleVector< T > KSingleVector< T >::operator- (const T val) const inline
Definition at line 308 of file KDataFrame.h.
References StringTo().
operator/() [1/2]
template<typename T > KSingleVector< T > KSingleVector< T >::operator/ (const KSingleVector< T > & obj) const inline
Definition at line 290 of file KDataFrame.h.
References StringTo().
operator/() [2/2]
template<typename T > KSingleVector< T > KSingleVector< T >::operator/ (const T val) const inline
Definition at line 324 of file KDataFrame.h.
References StringTo().
operator<()
template<typename T > KSingleVector< T > KSingleVector< T >::operator< (const T val) const inline
Definition at line 346 of file KDataFrame.h.
References KSingleVector< T >::push_back(), and StringTo().
operator<=()
template<typename T = std::string> KSingleVector< T > KSingleVector< T >::operator<= (const T val) const
operator=() [1/2]
template<typename T = std::string> KSingleVector & KSingleVector< T >::operator= (const KSingleVector< T > & obj) default
= 演算子のオーバーロード
operator=() [2/2]
template<typename T = std::string> KSingleVector & KSingleVector< T >::operator= (const std::vector< T > & obj) inline
Definition at line 176 of file KDataFrame.h.
References StringTo().
operator==()
template<typename T > KSingleVector< T > KSingleVector< T >::operator== (const T val) const inline
Definition at line 332 of file KDataFrame.h.
References KSingleVector< T >::push_back(), and StringTo().
operator>()
template<typename T > KSingleVector< T > KSingleVector< T >::operator> (const T val) const inline
Definition at line 346 of file KDataFrame.h.
operator>=()
template<typename T = std::string> KSingleVector< T > KSingleVector< T >::operator>= (const T val) const
operator[]() [1/2]
template<typename T = std::string> T & KSingleVector< T >::operator[] (std::size_t i) inline
Definition at line 178 of file KDataFrame.h.
References StringTo().
operator[]() [2/2]
template<typename T = std::string> const T & KSingleVector< T >::operator[] (std::size_t i) const inline
Definition at line 179 of file KDataFrame.h.
References StringTo().
push_back()
template<typename T > void KSingleVector< T >::push_back (const T & val) inline
値の追加.
Definition at line 237 of file KDataFrame.h.
References StringTo().
Referenced by KSingleVector< T >::append(), KSingleVector< T >::AsType(), KSingleVector< T >::operator!=(), KSingleVector< T >::operator<(), and KSingleVector< T >::operator==().
Scan()
template<typename T > void KSingleVector< T >::Scan ()
Definition at line 250 of file KDataFrame.h.
References StringTo().
Size()
template<typename T = std::string> size_t KSingleVector< T >::Size () inline
Definition at line 153 of file KDataFrame.h.
ToVector()
template<typename T = std::string> std::vector< T > KSingleVector< T >::ToVector () inline
std::vector<T>で取得
Definition at line 159 of file KDataFrame.h.
The documentation for this class was generated from the following file:
header/KDataFrame.h