Pandas module like CSV Parser: KStringFmt Namespace Reference
KStringFmt Namespace Reference
文字列を整形するために使う名前空間.
Functions
void GetStripCR (std::string &line)
改行文字を統一(windowsで採用されている改行コード"\r\n"の"\r"を削除)します.
void Strip (std::string &line)
文字の前後の半角、全角空白とタブを削除します.
template<class T >
T StringTo (const std::string &inp_val)
文字列を指定の型へ変換します
template<>
std::string StringTo< std::string > (const std::string &inp_val)
文字列を指定の型へ変換します
KVector StringTo (const std::string &inp_val)
文字列を自動的に整数、浮動小数点へキャストします.
Detailed Description
文字列を整形するために使う名前空間.
Function Documentation
GetStripCR()
void KStringFmt::GetStripCR (std::string & line)
改行文字を統一(windowsで採用されている改行コード"\r\n"の"\r"を削除)します.
Definition at line 44 of file KDataFrame.h.
Referenced by KDataFrame::GetcolumnStr(), KDataFrame::Open(), and KDataFrame::Scan().
StringTo() [1/2]
template<class T > T KStringFmt::StringTo (const std::string & inp_val)
文字列を指定の型へ変換します
Parameters
inp_val[in] 変換元の文字列
Returns
キャストされた値(int, double).
Note
C++14用に実装されました.C++17のStringTo関数はstdvariantによって「自動的に」文字列のキャストが行われます.
Definition at line 66 of file KDataFrame.h.
Referenced by KTypeConverter< const char *, To >::Convert(), KTypeConverter< std::string, To >::Convert(), and KDataFrame::Get().
StringTo() [2/2]
KVector KStringFmt::StringTo (const std::string & inp_val)
文字列を自動的に整数、浮動小数点へキャストします.
Parameters
inp_val[in] 変換元の文字列
Returns
自動キャストされた値[int, double, string].
文字列のパターンから自動的に整数、浮動小数点へ変換します. 変換できなかった場合変換は行われず、std::stringとして返します.
Note
std::variantがC+17以降はこちらの関数が機能します. 詳細はT StringTo(const std::string &inp_val)を参照してください.
Definition at line 99 of file KDataFrame.h.
StringTo< std::string >()
template<> std::string KStringFmt::StringTo< std::string > (const std::string & inp_val)
文字列を指定の型へ変換します
Parameters
inp_val[in] 変換元の文字列
Returns
キャストされた値(int, double).
文字列に対する関数templateの部分特殊化.
Note
C++14用に実装されました.C++17のStringTo関数はstdvariantによって「自動的に」文字列のキャストが行われます.
Definition at line 86 of file KDataFrame.h.
Strip()
void KStringFmt::Strip (std::string & line)
文字の前後の半角、全角空白とタブを削除します.
Definition at line 52 of file KDataFrame.h.
Referenced by KDataFrame::Open(), and KDataFrame::Scan().